auth:
  rootPassword: rootpassword
  username: user
  password: password
  database: stocat
  rootHost: "%"

timezone: Asia/Seoul

service:
  type: ClusterIP
  port: 3306

persistence:
  enabled: true
  size: 10Gi

args:
  - "--default-authentication-plugin=mysql_native_password"
  - "--character-set-server=utf8mb4"
  - "--collation-server=utf8mb4_general_ci"
  - "--init-connect=SET NAMES utf8mb4"
