apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}-auth
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
stringData:
  rootPassword: {{ required "auth.rootPassword is required" .Values.auth.rootPassword | quote }}
  userPassword: {{ required "auth.password is required" .Values.auth.password | quote }}
